# Disable the default crafting recipe (the ability of copying) for these Smithing Templates
# Only accepts Material format: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
disableCrafting:
- RIB_ARMOR_TRIM_SMITHING_TEMPLATE
- VEX_ARMOR_TRIM_SMITHING_TEMPLATE
- EYE_ARMOR_TRIM_SMITHING_TEMPLATE
- WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
- SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
- TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
- SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
- WARD_ARMOR_TRIM_SMITHING_TEMPLATE
- SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
- COAST_ARMOR_TRIM_SMITHING_TEMPLATE
- DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
- SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
- WILD_ARMOR_TRIM_SMITHING_TEMPLATE
- RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
- SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
- HOST_ARMOR_TRIM_SMITHING_TEMPLATE
- NETHERITE_UPGRADE_SMITHING_TEMPLATE
- FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
- BOLT_ARMOR_TRIM_SMITHING_TEMPLATE

# Remove these Smithing Templates from loot generation (for example: generated Loot Chests)
# Only accepts Material format: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
removeGeneratedLoot:
- RIB_ARMOR_TRIM_SMITHING_TEMPLATE
- VEX_ARMOR_TRIM_SMITHING_TEMPLATE
- EYE_ARMOR_TRIM_SMITHING_TEMPLATE
- WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
- SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
- TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
- SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
- WARD_ARMOR_TRIM_SMITHING_TEMPLATE
- SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
- COAST_ARMOR_TRIM_SMITHING_TEMPLATE
- DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
- SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
- WILD_ARMOR_TRIM_SMITHING_TEMPLATE
- RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
- SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
- HOST_ARMOR_TRIM_SMITHING_TEMPLATE
- NETHERITE_UPGRADE_SMITHING_TEMPLATE
- FLOW_ARMOR_TRIM_SMITHING_TEMPLATE
- BOLT_ARMOR_TRIM_SMITHING_TEMPLATE

# Remove these Smithing Templates from brushing loot
# Only accepts Material format: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
removeBrushLoot:
- HOST_ARMOR_TRIM_SMITHING_TEMPLATE
- SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
- RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
- WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE

# Remove all Smithing Templates from mob loot (currently: Elder Guardians)
removeMobLoot: true

# Set this to true if you want see a notification on the console, every time the pluing removes a loot
debug: false
